### ISSUE TITLE
SeLoger API change

### ISSUE THREAD

**Issue by kissu** [axeleroy/untoitpourcaramel#3]
Hey ! :wave: 
Apparently, SeLoger's API has changed recently.
I cannot find a way to find the new one...

Do you have an idea ? :smile:

**Comment by axeleroy** [comment]
Hello!

I found out the change last summer while [rewriting this project with Angular/AWS Lambda](https://github.com/axeleroy/commechezsoi).

At the time the API changed to work with [an authentication token that can be requested](https://github.com/axeleroy/commechezsoi/blob/master/awslambda/src/main/java/sh/leroy/axel/commechezsoi/awslambda/handler/seloger/SeLogerAuthenticateHandler.java) through `/api/v1/security/authenticate` with set parameters.
Once the token has been created, you could request the `/api/v1/listings/search` endpoint with parameters in a JSON object and [get a list of ads](https://github.com/axeleroy/commechezsoi/blob/master/awslambda/src/main/java/sh/leroy/axel/commechezsoi/awslambda/handler/seloger/SeLogerSearchHandler.java).
And to [get the ad's details](https://github.com/axeleroy/commechezsoi/blob/master/awslambda/src/main/java/sh/leroy/axel/commechezsoi/awslambda/handler/seloger/SeLogerDetailHandler.java) you had to call `/api/v1/listings/` with the id of the ad.

I do not know if it has changed since then, as I have not worked on the project since last fall.

Feel free to take a look into my [AWS Lambda clients](https://github.com/axeleroy/commechezsoi/tree/master/awslambda/src/main/java/sh/leroy/axel/commechezsoi/awslambda) ;)
